### ISSUE TITLE
chance.country() do not exist

### ISSUE THREAD

**Issue by JustDADE** [chancejs/chancejs#137]
Basically the title says all. [country()](http://chancejs.com/#country) is inside the documentation, but missing in source code.

P.S: I've just noticed you've added it 1 day ago. It's still missing on webpage/bower/npm, hope we'll see it soon.

**Comment by timohofmeijer** [comment]
Would you mind making this available via bower also? :yum:

**Comment by oliversalzburg** [comment]
In the meanwhile, you can also tell bower to use a specific branch or commit: `victorquinn/chancejs#develop` should work.

**Comment by timohofmeijer** [comment]
Thanks for the tip, and for all your work. Awesome lib, much appreciated!

**Comment by victorquinn** [comment]
Sorry again, should be all set now!
