### ISSUE TITLE
Provide more forgiving "pick" method

### ISSUE THREAD

**Issue by thrar** [chancejs/chancejs#173]
I'm using chancejs to pick elements from an array. I don't know in advance how many elements my array has and I also don't know how many elements I need to pick. Occasionally, the array may be empty or there may be only one element to pick.

My problem is that currently, I need to check for all these cases:
- If the array is empty, chancejs would throw an error, even if I'm only selecting 0 elements from it.
- If I'm selecting just 1 element, I get the element itself rather than an array containing it.
- If I select multiple elements I get them in an array.

My code looks like this (CoffeeScript):
```coffeescript
  if list.length is 0 then return list
  if Math.min(number, list.length) is 1 then return [chance.pick list]
  return chance.pick list, Math.min(number, list.length)
```

Is it possible to make the method more forgiving of edge cases? I would like this behavior:
- Return an empty array if picking 0 elements from an empty array
- Return an array containing just 1 element when selecting 1 element. Perhaps this would have to be a new method to allow the pick method to stay backwards compatible.

With the new behavior, picking any number of elements from an array of arbitrary length could be simplified to just:
```coffeescript
  return chance.pick list, Math.min(number, list.length)
```

**Comment by oliversalzburg** [comment]
As you've already mentioned, this might be better suited in a separate method, because the intent of `pick()` is to *pick* a single element out of an array and the method is used for just that in several places internally.

I wrote a small patch anyway to a discussion going :D

**Comment by leesei** [comment]
I think this is fixed with the introduction of `pickone()` and `pickset()` API (undocumented).

**Comment by victorquinn** [comment]
This was indeed fixed with `pickone()` and `pickset()` and the [docs](http://chancejs.com/#pickone) have been updated accordingly.
