### ISSUE TITLE
Generate a random svg?

### ISSUE THREAD

**Issue by franciscop** [chancejs/chancejs#193]
Is it within the scope of _chance_ to generate a random svg? I think this might be doable (and I'm ready to give it a try) in javascript. I'm not looking for anything complex, just a background colour and maybe a couple of lines on top of it. The output would be a string that later you can inject in the DOM or save as a file.

**Comment by franciscop** [comment]
Well here it is: [**DEMO**](https://jsfiddle.net/franciscop/819Lr84a/embedded/result/) and [jsfiddle](http://jsfiddle.net/franciscop/819Lr84a/). This made me realize that the colors generated from `chance.color()` could use [please.js](http://www.checkman.io/please/), maybe like `chance.color({ please: true });`. If it's within the scope I'll make it into a PR and test it

**Comment by oliversalzburg** [comment]
That is pretty sweet.

**Comment by victorquinn** [comment]
Heck yeah, that's totally rad!

**Comment by franciscop** [comment]
The default seems good enough. Some examples (I *did* cherry-pick some, but not too much):

![svg1](https://cloud.githubusercontent.com/assets/2801252/8889470/95c35152-3316-11e5-8a04-7569446281f9.png)
![svg2](https://cloud.githubusercontent.com/assets/2801252/8889471/95c511ea-3316-11e5-957a-364e8ebca2db.png)
![svg3](https://cloud.githubusercontent.com/assets/2801252/8889472/95c53e68-3316-11e5-9cd5-1ee3b9d4ceaa.png)
![svg4](https://cloud.githubusercontent.com/assets/2801252/8889473/95c8ad64-3316-11e5-8b3a-225d51655c8f.png)

Example with the defaults:

    // Generate a random svg image with the elements: circles, triangles and lines
    chance.svg({
        
        // Set the maximum radius for circle and a size-related feature for triangles
        // Computing the **real** max-size for triangles is not really relevant
        max_size: 30,

        // Number of lines, circles and triangles generated
        // Note: some of them might fall outside the image
        lines: 20,
        circles: 10,
        triangles: 10,

        // Opacity of the elements
        opacity: 0.3,

        // Background color for the svg
        background: chance.color()
    });

While a lot more of options could be provided and fine-tuning, similarly to Moment.js, I think this is good enough for the scope of the library as a whole. I'll do a PR when I get some time.

**Comment by franciscop** [comment]
I never did a PR
