### ISSUE TITLE
Seed not repeatable when using mixins

### ISSUE THREAD

**Issue by xarvh** [chancejs/chancejs#204]
This affects chance 0.7.7 on Node.js.
To reproduce:

```
var Chance = require('chance');

function make() {
  var chance = new Chance(34958);
  chance.mixin({company: function() {return '' + chance.first() + '-' + chance.first() + ' LTD.';}});
  return chance;
};

var c1 = make();
var c2 = make();

console.log(c1.last());
console.log(c1.company());
console.log(c2.last());
console.log(c2.company());
```

`c1` and `c2` should provide exactly the same output, but this is not the case.

The problem is that `Chance.prototype.mixin()` replaces the prototype methods rather than the instance ones.
Since `Chance.prototype.mixin()` is an instance method, it should NOT affect other instances.

Problem seems to be at https://github.com/victorquinn/chancejs/blob/develop/chance.js#L280 : `this` should be modified instead of `Chance.prototype`.

**Comment by oliversalzburg** [comment]
Try this instead:
```js
function make() {
  var chance = new Chance(34958);
  chance.mixin({company: function() {return '' + this.first() + '-' + this.first() + ' LTD.';}});
  return chance;
};
```

**Comment by xarvh** [comment]
This does work, but it's still wrong.

Instance methods affect the whole class.
```
var Chance = require('chance');

function make(name) {
  var chance = new Chance(34958);
  chance.mixin({company: function() {return name;}});
  return chance;
};

var c1 = make('apple');
var c2 = make('pear');

console.log(c1.company());
console.log(c2.company());
```

If this is the desired behavior, `mixin` should be a class method, not an instance one.

**Comment by mcschroeder** [comment]
Bumping this old thread, because I just ran into this very issue (with v1.1.7). I too was under the impression that mixins were per-instance (and it really makes no sense that they wouldn't be, with this API). What's worse, the documentation itself uses mixins in a way that makes it impossible to obtain repeatable results (by using `chance` directly, instead of using `this`). 

This is a **major bug**, in my opinion.
