### ISSUE TITLE
Update website.

### ISSUE THREAD

**Issue by alejandronanez** [chancejs/chancejs#222]
Hey good morning,

We need to update the website with the `avatar()` method documentation.

Thanks!

**Comment by catalinmiron** [comment]
+1 for this. I'm currently working on a project that use [.avatar()](https://github.com/victorquinn/chancejs/blob/master/chance.js#L872-L951) but I couldn't get it working without looking at the implementation. More details below, if other people has troubles:

```javascript
// Example of using avatar
chance.avatar({fallback: 'monsterid', protocol: 'http'})
```

**Comment by leesei** [comment]
Seems link changes 0.7 was not documented.

**Comment by victorquinn** [comment]
Done!

http://chancejs.com/#avatar
