### ISSUE TITLE
[doc] Quotes in Markdown 'string' turned to `string` in HTML

### ISSUE THREAD

**Issue by leesei** [chancejs/chancejs#238]
I found this when copy-and-pasting codes from 

These are copies from http://chancejs.com/, note the quotes are not valid JavaScript.

```js
var Chance = require(‘chance’);
var chance1 = new Chance(“foo”);
var chance2 = new Chance(“bar”);
```

There should be an options equivalent to this [smartypants](https://www.npmjs.com/package/marked#smartypants) that should be turned off.

PS. congrats to the 1.0 release

**Comment by leesei** [comment]
Update:
I used [jekyll/docker](https://github.com/jekyll/docker) to serve `gh-pages` locally and the quotes are not converted.

**Comment by victorquinn** [comment]
I changed the markdown rendering engine from `rdiscount` to the default and that seemed to fix it!
