### ISSUE TITLE
Unique integer in a range error

### ISSUE THREAD

**Issue by edencorbin** [chancejs/chancejs#243]
I may just be missing how to do this, but if I pass in a range using unique it gives me an error that the first argument must be a function.

chance.unique(chance.integer({min: 0, max: 100000}), 100);

This works fine, but is not what I want:

chance.unique(chance.integer, 100);

**Comment by oliversalzburg** [comment]
Maybe this is what you're looking for?

```js
chance.unique(chance.integer.bind(chance,{min: 0, max: 100000}), 100);
```

**Comment by edencorbin** [comment]
That worked perfect, thanks allot! Great module too.

**Comment by victorquinn** [comment]
What @oliversalzburg suggested will work though it's even easier. Chance accepts the options as a third parameter so the following will also work:

```js
chance.unique(chance.integer, 100, {min: 0, max: 100000});
```

**Comment by edencorbin** [comment]
Also, great, thanks! I didn't notice that in the documentation section on unique, but perhaps I missed it.

**Comment by victorquinn** [comment]
Ooof you're right, not very well documented, I'll fix that
