### ISSUE TITLE
suggestions for pull request

### ISSUE THREAD

**Issue by therealpecus** [chancejs/chancejs#245]
Hello Victor & all,

I have never contribute to a OSS project before, but I have been working to extend Chancejs in order to better and more fully support internationalisation. This issue is actually to ask if these contributions can be merged into the main development trunk and how to best do so.

ATM I have:
- enriched the name and last name database sourcing data from census open data (Italy)
- added country support to a few geographical generators (such as provinces, regions/states, street suffixes, etc.), with corresponding localized data (region names, province names, etc.) 
- extended chance.dollar to chance.euro for us european geeks
- added a vat generator (which currently provides Italian VAT codes)
- added a SSN generator for Italian Codice Fiscale

[edit]
Unit testing works as expected (tests have been added to the test suite for the new generators). Unfortunately, I don't seem to find the documentation page (http://chancejs.com), but I can support Victor in updating it (I will prepare the relevant snippets to merge with the page).

There do not seem to be a particular coding style or code commenting, nor strict rules as to how to prepare commits (squashed, atomic, ...). This is the kind of feedback I am looking for before submitting a PR (or moving these generators out from chance and into mixins, despite being more universal than local).
[/edit]

I look forward to any feedback.

**Comment by akre54** [comment]
I think in general it's better to err on the side of action. The project maintainers can always clean up code styling later, or ask you to squash your commits. Don't let process deter you from helping to improve the project!

**Comment by victorquinn** [comment]
/agree * 1000 to @akre54 's comment

Apologies on my long response here, missed this somehow.

Anyway, yes changes/improvements are quite welcome! We can hash out the details in the pull request.

As for docs, they're a branch on this repo (the `gh-pages`) branch so you can make them yourself as a separate pull request or I can go through them if you'd rather not muck with the documentation page.

**Comment by therealpecus** [comment]
Great! 2 PRs have been made, one for code, one for the documentation page.

**Comment by victorquinn** [comment]
Closing this issue since your PRs have been merged. Thanks again for contributing!
