### ISSUE TITLE
'weighted' function modifies passed in array - is this by design?

### ISSUE THREAD

**Issue by spayton** [chancejs/chancejs#250]
The weighted function removes any values <= 0 from the 'weight' array and their corresponding entry in the 'arr' array, as these arrays are passed in array references the modification will occur to the source arrays.

This behaviour isn't documented and would probably be unexpected - it's just caught me out.

Unless this is by design it should be changed to use a local copies.  The weighted function will also fail if the passed in array were sealed and it tried to remove entries from them.

**Comment by spayton** [comment]
I've done a pull request  #251 to prevent modification of the source arrays.

I can see a case where source array modification would be desirable, where the caller wants to successively pull values from a shrinking pool, but this isn't the behaviour you would expect from this function.  This behaviour should be added by way of another function or by way of an extra parameter allowing it to remove the 'used' entry from the source arrays.

**Comment by victorquinn** [comment]
Totally not by design, crappy oversight on my part. We used to do this in a few places, I thought most had been fixed but obviously this got missed so thanks for the PR!
