### ISSUE TITLE
birthday() with type option can generate birthdays outside of the age range, plus a few minor issues

### ISSUE THREAD

**Issue by mdsakalu** [chancejs/chancejs#255]
### Main issue
Since `birthday()` just uses a random year, it can generate birthdays outside of the age range. For instance, `birthday({type: 'adult'})` could result in a birthday of 12/12/1998, which means that a person with that birthday is still 17, not 18.

### Other issues
I noticed that the age ranges were inconsistent through the code and tests. For instance, in some places the max age was 100, in others it was 120.

I think that the minimum age for child should be 0, not 1.

**Comment by leesei** [comment]
With the PR merged, can this be closed?

**Comment by mdsakalu** [comment]
Yes this can be closed.
