### ISSUE TITLE
Support for gender other than male or female

### ISSUE THREAD

**Issue by hilkeheremans** [chancejs/chancejs#258]
So, this issue is probably going to put a nice smile on some folks' faces, but let me situate this a little.

In more and more countries - including Belgium and Germany - there is a growing call for equal treatment of genders other than 'male' or 'female'. Think of transgenders and other _it's complicated_ type of situations (not judging here). 

Since eventually more and more backend systems will have to cope with this type of situation, I was wondering if it would be possible to extend the `chance.gender()` function a little bit to (optionally, I suppose) allow for random generation of additional genders, or for an "unknown" gender type. Something like:

    chance.gender(['Unknown', 'Trans', 'whatever else there is'])

I fully well realise it's just as convenient to opt for something like `chance.pickOne(['Male', 'Female', ...])` and that it's consequently really low priority, but I thought I'd throw this one into the mix for those who might feel left out!

**Comment by victorquinn** [comment]
Closing this because it was fixed with #259
