### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by errorx666** [chancejs/chancejs#265]
I would like to use this library with [TypeScript](/Microsoft/TypeScript).  To do so requires a definition file with typing information.  Type definition files can be installed with [Typings](/typings/Typings) from a number of sources, including github, bower, and npm.

I can prepare a PR if there is interest.

**Comment by oliversalzburg** [comment]
You should be able to just use https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/chance

**Comment by errorx666** [comment]
Huh.  I wonder why `typings` didn't see that one.
