### ISSUE TITLE
Assume generator output is a promise.

### ISSUE THREAD

**Issue by airtonix** [chancejs/chancejs#275]
This would allow for mixins to return a promise, which then lets us create async generators..

**Comment by victorquinn** [comment]
Well first, I wouldn't want to make this change to the entire library as that would change it dramatically and break tons of code.

But beyond that, there is nothing preventing you from creating a mixin which returns a promise and using that. For example:

```js
chance.mixin({
    'asyncFirstname': function() {
        return new Promise(function(resolve, reject) {
            setTimeout(function() {
                resolve(chance.first());
            }, 100);
        }));
    }
});
```

That mixin returns a promise, waits 100ms then generates and resolves with a first name. Same could be done with any async/promise generating code like calling out to a DB or whatever.

You could also use a third-party library to wrap all of Chance's methods in Promises. For example, [Bluebird's `promisifyAll`](http://bluebirdjs.com/docs/api/promise.promisifyall.html) method could be used to make each of the Chance methods have a promise returning analogue.

```js
var chance = Promise.promisifyAll(new Chance());

// This returns a promise
chance.firstNameAsync().then(function(first) {
    console.log('First: %s', first);
});
```

So while I appreciate the sentiment here, the same could be accomplished without modification to Chance.
