### ISSUE TITLE
[FEATURE REQUEST] Generating Light and Dark Colors

### ISSUE THREAD

**Issue by caimen** [chancejs/chancejs#289]
I would like to be able to generate only light or only dark colors.  Since generally you need a color that either works on a dark or light background I think it would be useful.  I'm certainly running into this issue with my project right now.  I was digging into the library a bit, but wasn't sure how I would best implement it.  Light and dark is somewhat subjective.  Any suggestions on how it should best be implemented?

For now I'm using something similar to marked answer in this question.
http://stackoverflow.com/questions/11225050/how-to-generate-light-colour-shades-in-javascript

**Comment by caimen** [comment]
I thought about this a bit, and maybe it would would work best if we can just send a minimum and maximum rgb or hex values.  I might try and implement something like this.

**Comment by caimen** [comment]
So after looking through the code a bit I made a change that works well for RGB.  This essentially lets you generate and RGB color within any range you like making it easy to generate light and dark colors.

```
        function rgb(hasAlpha) {
            var rgbValue    = (hasAlpha)    ? 'rgba' : 'rgb';
            var alphaChanal = (hasAlpha)    ? (',' + this.floating({min:0, max:1})) : "";
            var colorValue  = (isGrayscale) ? (gray(this.natural({min: minR, max: maxR}), ',')) : (this.natural({min: minR, max: maxR}) + ',' + this.natural({min: minR, max: maxR}) + ',' + this.natural({max: 255}));

            return rgbValue + '(' + colorValue + alphaChanal + ')';
        }

        function hex(start, end, withHash) {
            var symbol = (withHash) ? "#" : "";
            var expression = (isGrayscale ? gray(this.hash({length: start})) : this.hash({length: end}));
            return symbol + expression;
        }

        options = initOptions(options, {
            format: this.pick(['hex', 'shorthex', 'rgb', 'rgba', '0x', 'name']),
            grayscale: false,
            casing: 'lower', 
			minR: 0,
			maxR: 255, 
			minG: 0,
			maxG: 255, 
			minB: 0, 
			maxB: 255
        });
```

However for hex colors I feel like we need a new basic random function to specifically generate hex numbers with the option of minimum and maximum values.  This would help me finish the random colors with minimum and maximum values for Red Green and Blue.  Can someone let me know if they think I'm on a good track here?  I've never contributed to an open source project so I would be interested to know what anyone thinks so far.

**Comment by caimen** [comment]
I ended up spending quite some time with this and have tried to standardize things naming wise a bit with the rest of the library.  It is currently working now.  I'm still trying to think of ways to reduce the number options you need to send.  However more options are always better I think.  It will even let you grayscale certain color range.  Will likely do some more testing and review before I do an actual pull request, but this will give you an idea of what you can do with it.

```
//Random Light Red sending minimum needed options
var light_red = chance.color({format: 'hex', min_red: 200, max_red: 255, max_green: 0, max_blue: 0, min_alpha: .2, max_alpha: .3});

//Random Light Blue by sending all options
var light_blue = chance.color({format: 'rgba', min_red: 0, max_red: 0, min_green: 0, max_green: 0, min_blue: 200, max_blue: 255, min_alpha: .2, max_alpha: .3});

//Random Green Grayscalled
var c = chance.color({format: 'hex', grayscale: true, max_red: 0, min_green: 200, max_green: 255, max_blue: 0});
```

Also in order to program the above I needed a random hex number generator with minimum and maximum range.  So I've added this.

```
     /**
     *  Return a random hex number as string
     *
     *  NOTE the max and min are INCLUDED in the range. So:
     *  chance.hex({min: '9', max: 'B'});
     *  would return either '9', 'A' or 'B'.
     *
     *  @param {Object} [options={}] can specify a min and/or max and/or casing
     *  @returns {String} a single random string hex number
     *  @throws {RangeError} min cannot be greater than max
     */
    Chance.prototype.hex = function (options) {
        options = initOptions(options, {min: 0, max: MAX_INT, casing: 'lower'});
        testRange(options.min < 0, "Chance: Min cannot be less than zero.");
		var integer = chance.natural({min: options.min, max: options.max});
		if (options.casing == 'upper') {
			return integer.toString(16).toUpperCase();
		}
		return integer.toString(16);
    };

```

As I said before I'm very new to github and open source contribution, if I'm doing something wrong please let me know!

**Comment by caimen** [comment]
@victorquinn I'm interested in submitting a pull request with these changes.  Do I need permission from you to do that?  So far I've been getting permission issues.

**Comment by victorquinn** [comment]
You shouldn't need any permission to submit a pull request and this would be a welcome addition! 

You won't be able to push directly to this repo but you should be able to fork the repo, make your changes there, and submit your PR. 

Once it's submitted I'll just review and merge.

Cheers,
Victor

**Comment by caimen** [comment]
Now that PR #290 has been merged, I think it's safe to close this issue.
