### ISSUE TITLE
Component.io doesn't exist anymore

### ISSUE THREAD

**Issue by franciscop** [chancejs/chancejs#291]
Component.io has been discontinued and now the link in the documentation serves as advertising for a domain on sales. Is there a way to edit the documentation to remove it ourselves? Otherwise this is just a notice.

**Comment by victorquinn** [comment]
Oof yeah we should certainly remove it then!

I'm going to leave this open until I can edit everything to remove it. It's not just docs, but also some of the code files as well to support it.
