### ISSUE TITLE
Testing failing with NPM 3.0.0

### ISSUE THREAD

**Issue by franciscop** [chancejs/chancejs#292]
A clean install & test of Chance.js in a modern Node.js environment now fails. This is probably due to [breaking changes in NPM 3.0.0](http://dailyjs.com/2015/06/26/npm-3/):

> Your dependencies will now be installed maximally flat. Insofar as is possible, all of your dependencies, and their dependencies, and THEIR dependencies will be installed in your project's node_modules folder with no nesting.

And this is the error message, failing on `npm test`:

    > chance@1.0.4 test [...]/chancejs
    > grunt test-ci

    >> Tasks directory "[...]/chancejs/node_modules/grunt-js-test/node_modules/grunt-mocha/tasks" not found.

    Running "jshint:all" (jshint) task
    >> 16 files lint free.

    Running "js-test" task
    >> Started proxy web server on port 8983.

I tried to access that folder manually and it doesn't exist (there's no `grunt-mocha` inside `grunt-js-test/node_modules`). This is probably the explicit line giving trouble from `grunt-js-test`:

> grunt.loadTasks(path.join(__dirname, '../node_modules/grunt-mocha/tasks'));

Which is line 17 of `grunt-js-test/tasks/js-test.js`. When I access to `grunt-js-test/node_modules`, there's only a single `lodash` from `ls`. However, the package `grunt-mocha` is a sibling of `chancejs/node_modules`:

    /chancejs
      /node_modules
        ...
        /grunt-mocha
        /grunt-js-test
          /node_modules
            [grunt-mocha not here]

I see that you found the same problem (google found it) in [Travis CI](https://travis-ci.org/chancejs/chancejs/jobs/151687235), how did you solve it? I'll copy/paste this to `grunt-js-test` so they can fix it.

**Comment by victorquinn** [comment]
Ugh this whole testing mess is something I've been meaning to sort out for awhile...

In brief it's a mess because the tooling back when I built it circa 2012 wasn't where it is today. I really wanted to make sure it was tested using PhantomJS to ensure it would work client-side in the browser (anything that works there should work server-side as well). 

At some point one of the dependencies broke and I had to fork it to make things work. Now it's just a big mess.

This should probably be unwound and refactored to use modern test tooling that doesn't require my fork.

**Comment by franciscop** [comment]
I see, I don't know anything about coverage analysis, but I did use PhantomJS before with Grunt and it's just this:

```js
mocha_phantomjs: {
  all: './tests.html',
  options: {
    'web-security': false    // Allow CORS
  }
},
```

Then I would include the script from `tests.html` with a simple `<script></script>` and it worked both on any browser and on PhantomJS. You can see [the full Gruntfile.js I used here](https://github.com/umbrellajs/umbrella/blob/master/Gruntfile.js) in case you are interested.

**Comment by victorquinn** [comment]
Fixed!
