### ISSUE TITLE
John as female first name

### ISSUE THREAD

**Issue by MatthieuLemoine** [chancejs/chancejs#293]
Hi!

John is part of the female first name list while in the #45 PR, which allows gender specific first name generation, the contributor @xshyamx use this very case as an example to justify the need of this feature : 

>  It is mainly for generating demo profiles and for that the random name and gender must match. Eg. I cannot have a Female with first name John. As of now we cannot avoid that possibility in Chance.js

**Comment by caimen** [comment]
I just submitted a PR for this as I use these methods as well for a game I'm working on.
