### ISSUE TITLE
MersenneTwister implementation requires copyright notice to be distributed

### ISSUE THREAD

**Issue by kamranayub** [chancejs/chancejs#296]
Just a minor thing but noticed after reviewing the source for the MT algorithm, Chance.js *must* include the full copyright notice in its source code and the LICENSE file according to the terms of the license.

https://gist.github.com/banksean/300494

```
     1. Redistributions of source code must retain the above copyright
        notice, this list of conditions and the following disclaimer.
 
     2. Redistributions in binary form must reproduce the above copyright
        notice, this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.
```

A link to the gist is not sufficient under these terms.

**Comment by victorquinn** [comment]
Ahh good catch, never noticed that! I'll leave this issue open until I can get this live.
