### ISSUE TITLE
chance.color() broken in 1.0.5

### ISSUE THREAD

**Issue by evonsdesigns** [chancejs/chancejs#306]
Hello, I am receiving the following error after getting the 1.0.5 update:

>  ReferenceError: chance is not defined
19:15:49       at Chance.hex (node_modules/chance/chance.js:272:24)
19:15:49       at Chance.hex (node_modules/chance/chance.js:1125:27)
19:15:49       at Chance.color (node_modules/chance/chance.js:1177:30)

It appears that the following line assumed a chance variable was globally accessible:
`272: var integer = chance.natural({min: options.min, max: options.max});`

The fix should be replacing `chance.natural` with `this.integer`.

**Comment by victorquinn** [comment]
Oof that's not good, will fix ASAP!

**Comment by victorquinn** [comment]
This is published on npm as 1.0.6!
