### ISSUE TITLE
Proposal of `chance.locale()`

### ISSUE THREAD

**Issue by evonsdesigns** [chancejs/chancejs#307]
Hello, I'd like to propose a helper function called `locale()` that returns a random valid locale from an internal predefined list. The options could specify if the locale should include a region. 

Example:
`chance.locale() => 'de'`
`chance.locale({region: true}) => 'de-DE'`

**Comment by WriteCodeEveryday** [comment]
Implemented by https://github.com/chancejs/chancejs/pull/314.

Currently in review.

**Comment by evonsdesigns** [comment]
Thanks @WriteCodeEveryday and @victorquinn !
