### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by jpdimond** [chancejs/chancejs#318]
Hi there,

I'm getting this when installing chance via bower:

bower cached        https://github.com/victorquinn/chancejs.git#1.0.6
bower validate      1.0.6 against https://github.com/victorquinn/chancejs.git#*
bower new           version for https://github.com/victorquinn/chancejs.git#*
bower resolve       https://github.com/victorquinn/chancejs.git#*
bower download      https://github.com/victorquinn/chancejs/archive/1.0.7.tar.gz
bower extract       chance#* archive.tar.gz
bower EMALFORMED    Failed to read /var/folders/t4/mqmn7k_n1q165zz_r1zm_dgh0000gn/T/jpdimond/bower/1ea287f2ecbfd355c05b14f134d85007-53788-2yY4cY/bower.json

**Comment by jsJunky** [comment]
Additional error details:

Unexpected string in JSON at position 45

**Comment by victorquinn** [comment]
Hmmmmm weird let me investigate. Looks like bower is trying to download the 1.0.7 tar for the 1.0.6 version for some reason.

**Comment by victorquinn** [comment]
Ahhh I see the issue, pushing a fix shortly. Looks like when I bumped the version in the bower.json I accidentally removed a trailing comma :(

**Comment by jpdimond** [comment]
So easy to do, thanks so much for your quick response!

**Comment by victorquinn** [comment]
Ok, this is fixed, try again!

Also pushed a new version to npm (yay semantic versioning) so this is 1.0.8 everywhere.

**Comment by jpdimond** [comment]
Works, thanks!!
