### ISSUE TITLE
Seeding issue with require('chance').Chance() instantiation

### ISSUE THREAD

**Issue by panta82** [chancejs/chancejs#322]
If you instantiate chance without using the `new` keyword, as suggested [here](http://chancejs.com/#node), you will always get the same seed.

```javascript
var c1 = require('chance').Chance();
var c2 = require('chance').Chance();
console.log(c1.string() === c2.string()); // true
```

The problem is here:

```javascript
    // Constructor
    function Chance (seed) {
        if (!(this instanceof Chance)) {
            return seed == null ? new Chance() : new Chance(seed);
        }
        // the rest
    }
```

You handle `new`, but not `undefined`, which gets passed as the seed.

```javascript
require('chance').Chance().string() === require('chance').Chance(undefined).string() // true
```

If this is the desired behavior, I would suggest adding a big warning into the docs about the security implications.

**Comment by victorquinn** [comment]
Closing this since it is now published on npm as 1.0.10
