### ISSUE TITLE
Removing Pool Characters Programmatically

### ISSUE THREAD

**Issue by spencerthayer** [chancejs/chancejs#324]
I have a question about removing characters from a pool. Specifically, how would I strip the characters in the `ambiguous` variable from `document.write` of `chancePass.string` in realtime? The pool is currently using the variables `spaces`, `lowerCase`, `upperCase`, `digits`, and `special`.

To clarify, I'm asking about a solution within chance.js rather than using something like `.replace()` before calling `chancePass.string`. I understand there are other methods to get this done. If there isn't a chance.js solution please feel free to just close the ticket.

```javascript
    // STRING CREATION
    var lowerCase = "abcdefghijklmnopqrstuvwxyz";
    var upperCase = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    var digits = "1234567890";
    var special = "!@#$%^&*-_=+{}[]()|/\\\"\'`~,;:.\<\>";
    var ambiguous = "illL1o0O|";
    // USER VARIABLES
    var masterPass = "a test p@ssword";
    var siteName = "domain.com";
    var userProfile = "loginname";
    var characterLength = chance.integer({
        min: 4,
        max: 24
    });
    // GENERATE UNIQUE PASSWORD
    var chancePass = new Chance(masterPass, siteName, userProfile, characterLength);
    document.write(chancePass.string({
        length: characterLength,
        pool: lowerCase + upperCase + digits + special,
    }));
```

Thanks!

**Comment by spencerthayer** [comment]
Okay, I'm assuming that there is no chance.js specific method. RegEx is it.

**Comment by victorquinn** [comment]
Sorry I didn't respond to this sooner, I was in the woods backpacking this weekend so I didn't get to all of my email.

There is to way to explicitly remove characters from the pool at current but there is a way to define your own pool. 

I do think there is value in having this kind of exclusion, it just doesn't exist today.
