### ISSUE TITLE
chance.fbid() returns incorrect data type

### ISSUE THREAD

**Issue by sergii-tkachenko** [chancejs/chancejs#328]
Documentation example states that `chance.fbid()` returns a string, but the actual function returns a number.

Documentation:
```
chance.fbid()
=> "1000039460258605"
```

Node.js:
```
$ node
> const Chance = require('chance');
undefined
> const chance = new Chance();
undefined
> chance.fbid()
1000043241133378
> typeof chance.fbid()
'number'
```

**Comment by caimen** [comment]
@sergii-tkachenko

If Facebook ID's are always numbers then I would say the documentation needs to be changed to say always return a number.  My guess i the documentation is just incorrect and needs to be fixed.  Are Facebook ID's always numbers?

**Comment by sergii-tkachenko** [comment]
In [Graph API documentation](https://developers.facebook.com/docs/graph-api/reference/user/) they state that Facebook IDs are "numeric strings". I assume they reserve a right to move IDs to the alphanumeric namespace.

I'd recommend to convert `chance.fbid()` return value to a string, so it's consistent with FB's docs.

**Comment by caimen** [comment]
In that case I think yes, `chance.fbid()` should be a string.  I'll see if I can make a pull request this week, or feel free to yourself.  I support this change given the facebook documentation.

**Comment by sergii-tkachenko** [comment]
I can make a PR later this week.

**Comment by victorquinn** [comment]
👍 I think it should return a string also, happy to accept this PR if someone tackles it!
