### ISSUE TITLE
Suggestion for new method `pickOnce`

### ISSUE THREAD

**Issue by jaychsu** [chancejs/chancejs#329]
Sometimes we need to pick an item from an array but only get once.

And here is my concept to implement that:

```javascript
const arr = [ ... ];
const newArr = chance.shuffle(arr);

newArr.pop();
```

I'll submit a PR to do that if it makes sense.

**Comment by caimen** [comment]
I'm a little confused, what does this return?  If it's returning newArr then you are shuffling the passed in array and removing the last item from it.  pickOnce wouldn't be an appropriate name for that.  Can you clarify your idea a bit?
