### ISSUE TITLE
exclude values from result

### ISSUE THREAD

**Issue by malorus** [chancejs/chancejs#330]
Hi there, great library! Just have a question as I could not see a solution to this. Assuming I want to generate a random natural:

`chance.natural({min: 1, max: 20});`

Is there any way to exclude certain values? Let's say 14 should not be outputted. I know I can then call `chance.natural()` a second time but I wondered if there is a build-in possibility, like for example: 

`chance.natural({min: 1, max: 20, exclude: [14,16]});`

So you can determine an array of values which will be excluded from the result.

**Comment by victorquinn** [comment]
There is not! 

But I'd gladly accept a PR which would do that :)

**Comment by YahiaElTai** [comment]
Hey, I'm glad to help out with this one, can i do a PR and add it?

**Comment by victorquinn** [comment]
Yes, I'd love a PR @YahiaElTai
