### ISSUE TITLE
Pickset is slow for large arrays

### ISSUE THREAD

**Issue by vshulev** [chancejs/chancejs#335]
Calling the method `pickset` on a large array (tried it with an array of 20000 items) runs very slow. To fix this I am using the following function (which runs much faster) to pick a random set of items from an array:

```js
function pickset (arr, n) {
    return chance.n(chance.ingeter, n, { min: 0, max: arr.length - 1 }).map(i => arr[i])
}
```

I get the following when measuring the execution time for both functions:
- chance.pickset: **51.348977ms**
- custom pickset: **0.094814ms**

Would it be desirable to change the current implementation for `pickset`?

**Comment by victorquinn** [comment]
Oh nice, that's a much better solution @vshulev ! `pickset()` is mostly slow due to its use of `shuffle()` under the hood which is a very inefficient operation.

I'd gladly accept a PR with this implementation 😀

**Comment by vshulev** [comment]
@victorquinn PR #336 done. Let me know if it needs any improvements :)
