### ISSUE TITLE
[Feature Request] chance.falsy()

### ISSUE THREAD

**Issue by evonsdesigns** [chancejs/chancejs#360]
Returns any of the following [falsy values](https://developer.mozilla.org/en-US/docs/Glossary/Falsy):

* false
* null
* undefined
* 0
* NaN
* ''

**Comment by hugoiuri** [comment]
I created a pull request (#378) to solve this feature request.

**Comment by emahuni** [comment]
can you please put an alias to it, 'falsey'

**Comment by emahuni** [comment]
also I noticed that if you use the pool parameter it doesn't work as intended

**Comment by emahuni** [comment]
oh and close this issue
