### ISSUE TITLE
How to generate a string length>5

### ISSUE THREAD

**Issue by xwmyth8023** [chancejs/chancejs#377]
Now can generate a string with specify a length:
`chance.string({ length: 5 })`
but I want generate a string length > 5,
any suggestions? thanks!

**Comment by hugoiuri** [comment]
In this case you can use min parameter.

`chance.string({ min: 5 })`

**Comment by xwmyth8023** [comment]
![image](https://user-images.githubusercontent.com/29378004/43580969-c3d78c1e-9689-11e8-9af7-b2e4f2357b60.png)
It seems that usage doesn't work.
My code is 
`chance.string({ min: 6 })`
but it returns a string length=5

**Comment by hugoiuri** [comment]
It's really doesn't work.

I created this test and they failed:

`

test('string() can take just a min and obey it', t => {
    _.times(1000, () => {
        t.true(chance.string({ min: 6 }) >= 6)
    })
})

test('string() can take just a max and obey it', t => {
    _.times(1000, () => {
        t.true(chance.string({ max: 20 }) <= 20)
    })
})`

I will check this code here.

**Comment by hugoiuri** [comment]
I created a pull request to solve this problem #379

**Comment by xwmyth8023** [comment]
Thanks ever so.
