### ISSUE TITLE
What is the default seed?

### ISSUE THREAD

**Issue by yxliang01** [chancejs/chancejs#404]
I have consulted the docs of this library but I could not see what the default seed is when the seed is not provided. Did I overlook? Or, it's indeed not in the docs? If it's not in the docs, probably it's a good idea to add it.

Thanks

**Comment by seiyria** [comment]
The default is `null`, it seems: https://github.com/chancejs/chancejs/blob/master/chance.js#L31

**Comment by yxliang01** [comment]
@seiyria Thanks for your reply. However, the true seed is not really `null`. If so, https://github.com/chancejs/chancejs/issues/322 wouldn't be closed.

**Comment by seiyria** [comment]
Sorry, you seem to be right, but in that case, it would be `undefined`. To that end, the default seed the twister gets is a random value: https://github.com/chancejs/chancejs/blob/master/chance.js#L7183

**Comment by yxliang01** [comment]
@seiyria Hmm. Then am I right that if `seed` is not provided, then it would be a number that was returned by a function of the first random number from implementation's default random generator? And, that reduces to the implementation's default seed?

**Comment by victorquinn** [comment]
Yes if no seed is provided, it is indeed `undefined` and then we use `Math.random()` to generate a random one. 

Is there still an unresolved issue here?

**Comment by yxliang01** [comment]
@victorquinn @seiyria  Thanks for clarification. This can be closed now.
