### ISSUE TITLE
[Discussion/Feature Request]Ignore "package-lock.json"

### ISSUE THREAD

**Issue by VitorGultzgoff** [chancejs/chancejs#415]
Based on the fact that **_package-lock.json_** is automatically generated for general operations where the npm modifies **_node_modules_** or even **_package.json_**, will results in some cases like [PR #400 ](https://github.com/chancejs/chancejs/pull/400) which the focus wasn't modify a dependency, but because of _package-lock.json_ conflicts, the PR fails.
**1** - Nowadays it's not ignored in _.gitignore_, should not be ?
**2** - Is there a particular _scenario_ which wouldn't helps ?

**Comment by jafin** [comment]
This SO post tends to prefer it being checked in. Especially if you use npm 5+ in the build steps https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5
