### ISSUE TITLE
TLDs do not match IANA list

### ISSUE THREAD

**Issue by tpburch** [chancejs/chancejs#427]
We use chance extensively for generating test data for API calls. We have come across issues where `chance.email()` is generating invalid emails, based on validation requirements that the email should have a valid IANA TLD. 

Examples of this:
1. TLD: 'an' - this tld was retired in 2010
2. TLD: 'bq' - this tld is listed as a "country code", but has not been assigned so is currently not a valid TLD. 

While I wouldn't expect chance to maintain a list in parity with IANA, I would love to see one of two updates:
1. Remove any invalid  IANA values from the `tlds` list.
2. Update `tlds` to match the current IANA list.

I'm willing to submit a PR for either, but I'm not sure which (if either) would be the preferred approach.

**Comment by TimBailey-pnk** [comment]
Hi, we also are having random test failures.  We are using Joi to validate emails (https://hapi.dev/family/joi/?v=16.1.8) and it causes test failures when chance.email() returns a `.an` or `.eh` domain (this are just some examples of invalid tlds)

Joi internally uses "@hapi/Address" https://hapi.dev/family/address/?v=3.2.2#domainanalyzedomain-options which then validates against the "Official IANA" list from here http://data.iana.org/TLD/tlds-alpha-by-domain.txt

@tpburch Did you already make a PR for this change?  All we really need to to remove the invalid TLDs from the chancejs list so they are always valid.

**Comment by victorquinn** [comment]
FYI this is fixed and published on npm as `1.1.4`

**Comment by diogocampos** [comment]
Hi there, I'm also getting random test failures with Joi, just as described by @TimBailey-pnk above, even after updating to 1.1.4

**Comment by TimBailey-pnk** [comment]
Hi, confirmed still happening for me on 1.1.4

**Comment by josh18** [comment]
Is it worth adding a dependency to something like https://www.npmjs.com/package/tlds to ensure they stay in sync?

**Comment by TimBailey-pnk** [comment]
@victorquinn Will you accept a PR with the dependency https://www.npmjs.com/package/tlds ?

**Comment by victorquinn** [comment]
> @victorquinn Will you accept a PR with the dependency https://www.npmjs.com/package/tlds ?

No, not on the 1.0 branch, sorry. 

Chance currently has zero dependencies and I’d like to keep it that way until we have a build step. As is that would break browser compatibility because there is no build step on the 1.0 branch. 

After the move to 2.0 I’d happily accept it though.
