### ISSUE TITLE
.n() The first argument must be a function

### ISSUE THREAD

**Issue by djom20** [chancejs/chancejs#429]
Hi team,

Currently I'm facing this error with **n function**, because such as we can see in the documentation, we can use any chance function into the n function but right now I getting this error:

![image](https://user-images.githubusercontent.com/1834808/63045717-91ae4580-be96-11e9-90e7-24ff7fd4b78e.png)

and based on the documentation we can do this:

```javascript
let chance = require('chance').Chance()
let fn = chance.pickone(['text', 'naohter','ohter','more'])
let r = chance.n(fn, 3)
console.log('r', r)
```
Or 
```javascript
let chance = require('chance').Chance()
let r = chance.n(chance.pickone(['text', 'naohter','ohter','more']), 3)
console.log('r', r)
```
But it's not working as expected, so I really appreciate to know if there is any workaround for this issue.

**Comment by jonathansamines** [comment]
@djom20 Please look at https://runkit.com/jonathansamines/5d883d8845f343001bf97fb1 for a reference example of how to use `chance.n` in this scenario.

I would suggest taking the time to understand how this function works by reading the library documentation: https://chancejs.com/miscellaneous/n.html
