### ISSUE TITLE
[MAJOR] Invalid Country Codes

### ISSUE THREAD

**Issue by agrohs** [chancejs/chancejs#454]
It mentions on the documentation page for Country: https://chancejs.com/location/country.html that `By default, returns only the 2 letter ISO 3166-1 code for the country.`, however in the code it contains countries that are not ISO 3166-1 codes (such as `{"name":"Diego Garcia","abbreviation":"DG"}`).

The code for Country says that it was sourced from `https://github.com/umpirsky/country-list/blob/master/data/en_US/country.json` but that list does not contain only valid ISO 3166-1 codes/countries (as per `https://www.iso.org/obp/ui/#search/code/`).

This is causing test cases written with `chance.country()` to return invalid results that will fail when testing!

**Comment by victorquinn** [comment]
Hmm interesting, good catch! I’ll gladly merge a PR fixing this if you get to it before I have time
