### ISSUE TITLE
Request to remove retired ".tp" top-level domain

### ISSUE THREAD

**Issue by EugeneChang** [chancejs/chancejs#520]
Request to remove retired ".tp" top-level domain.

Public report from IANA:

https://www.iana.org/reports/2015/tp-report-20150126.html

Emails generated with retired top-level domain might not be accepted by some Email validators.

For example:

DomainValidator in Apache commons validator.

Reference:

Line 1911
https://commons.apache.org/proper/commons-validator/apidocs/src-html/org/apache/commons/validator/routines/DomainValidator.html

**Comment by somejeff** [comment]
I agree,  `.tp` has been replaced with `.tl`
https://en.wikipedia.org/wiki/.tl
