### ISSUE TITLE
[new feature] Allow chance.birthday({minAge, maxAge})

### ISSUE THREAD

**Issue by gerardolima** [chancejs/chancejs#561]
I need to generate birthday dates within a range of ages. This is not rocket science, but the code to calculate the correct upper and lower date limits is error-prone:
1. day range follows the rule currently used into `Chance.prototype.birthday`:
```js
min.setFullYear(currentYear - age - 1);
max.setFullYear(currentYear - age);
```
2. but the time range needs some fixes to consider days as whole -- as nobody "ceases" to be the birthday person at 7:32, for example -- making the full range actually greater than the given range, in years:
```js
// this is just pseudo-code, due to `setFulTime`
min.setFulTime('00:00:00.000');
max.setDate(dt.getDate() + 1)
max.setFulTime('00:00:00.000');
max.setMilliseconds(max.getMilliseconds() -1);
```
Besides, that, I think the semantics of this would be very _intuitive_ and easy to read.

**Comment by gerardolima** [comment]
If the project is open to, of course, I can contribute code.

**Comment by victorquinn** [comment]
Love it, would gladly accept a PR with this!

**Comment by gerardolima** [comment]
The PR is signed and contains change on the code and documentation.

**Comment by gerardolima** [comment]
> Love it, would gladly accept a PR with this!

hey, @victorquinn, I just noticed the PR was closed not merged; was there a technical issue I didn't notice?

**Comment by victorquinn** [comment]
No issue on my end, it looks like you closed it yourself, maybe an accident?

![Screen Shot 2022-09-09 at 2 12 37 PM](https://user-images.githubusercontent.com/660139/189416929-73453c75-0f75-4d71-83f4-396dc154b606.png)

**Comment by gerardolima** [comment]
🤦🏽 I noticed I haven't signed the commit on the first time and forced-pushed a signed version; maybe I closed the PR by mistake; I'll open another PR

**Comment by gerardolima** [comment]
hey, @victorquinn, I don't want to be _pushy_ , just checking if code needs changes.

**Comment by victorquinn** [comment]
Oh my bad @gerardolima I didn't get notified that it was re-opened -- will review now for you!

**Comment by gerardolima** [comment]
hey, @victorquinn, just a friendly reminder that I added the tests and fixed a bug found in the meanwhile ;)
