### ISSUE TITLE
Version 1.1.10 breaks on Node 8

### ISSUE THREAD

**Issue by rkorebrits-paystack** [chancejs/chancejs#575]
Since version `1.1.10`, installing `chance` breaks on repos with Node 8. This means that any `package.json` with a `~` or `^` on version `1`/`1.1` will break.
It would have been nice if Chance would also have increased their version to indicate a potential breaking change

**Comment by whatbird** [comment]
this version also adds the dependency `[gulp-uglify-es](https://www.npmjs.com/package/gulp-uglify-es)` which is unmaintained and brings with it a hefty dependency tree. 

(this also seems possible unintentional)

**Comment by victorquinn** [comment]
oof yes definitely a bug that should be in `devDependencies` good catch
